# Generated by Django 3.0.2 on 2020-01-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
    ]
